//! `OBJECT` — JavaScript wrappers for Liquers core objects.
//!
//! Conventions, applied uniformly (`OBJECT08`):
//!
//! - **Construction goes through the Rust parser.** `Query.parse` / `Key.parse` call
//!   `liquers_core::parse`; the grammar is never reimplemented in JavaScript, so a wrapper can
//!   never disagree with the Rust parser or fall behind a grammar change.
//! - **Every wrapper owns its core object.** Nothing borrows, so no wrapper can outlive what it
//!   points at.
//! - **Wrappers are immutable.** Operations that would change one return a new wrapper.
//! - **Equality is `equals()`, not `===`.** Two wrappers around equal core objects are distinct
//!   JavaScript handles; `===` compares the handles and would say `false`.
//! - **`free()` is generated by `wasm-bindgen`** and using a freed handle throws. That is the
//!   documented lifetime (`OBJECT05`); it is not reimplemented here.

use liquers_core::parse::{parse_key, parse_query};
use liquers_core::query::{Key, Query};
use wasm_bindgen::prelude::*;

use crate::error::liquers_error_to_js;

/// A Liquers query.
#[wasm_bindgen(js_name = Query)]
#[derive(Clone)]
pub struct LiquersQuery {
    inner: Query,
}

#[wasm_bindgen(js_class = Query)]
impl LiquersQuery {
    /// Parses query text. Invalid text rejects with a `LiquersError` carrying the parse position.
    pub fn parse(text: &str) -> Result<LiquersQuery, JsValue> {
        parse_query(text)
            .map(|inner| LiquersQuery { inner })
            .map_err(liquers_error_to_js)
    }

    /// The canonical encoding of this query.
    pub fn encode(&self) -> String {
        self.inner.encode()
    }

    #[wasm_bindgen(js_name = toString)]
    pub fn to_string_js(&self) -> String {
        self.inner.encode()
    }

    /// Structural equality, compared through the canonical encoding.
    ///
    /// Not `===`: each wrapper is its own JavaScript handle, so identity comparison would report
    /// `false` for two wrappers around the same query.
    pub fn equals(&self, other: &LiquersQuery) -> bool {
        self.inner.encode() == other.inner.encode()
    }

    #[wasm_bindgen(js_name = isEmpty)]
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    /// The filename this query's result would be given, when the query specifies one.
    #[wasm_bindgen(getter)]
    pub fn filename(&self) -> Option<String> {
        self.inner.filename().map(|f| f.encode().to_string())
    }
}

impl LiquersQuery {
    pub fn inner(&self) -> &Query {
        &self.inner
    }

    pub fn from_query(inner: Query) -> Self {
        LiquersQuery { inner }
    }
}

/// A Liquers store key.
#[wasm_bindgen(js_name = Key)]
#[derive(Clone)]
pub struct LiquersKey {
    inner: Key,
}

#[wasm_bindgen(js_class = Key)]
impl LiquersKey {
    /// Parses key text. Invalid text rejects with a `LiquersError`.
    pub fn parse(text: &str) -> Result<LiquersKey, JsValue> {
        parse_key(text)
            .map(|inner| LiquersKey { inner })
            .map_err(liquers_error_to_js)
    }

    pub fn encode(&self) -> String {
        self.inner.encode()
    }

    #[wasm_bindgen(js_name = toString)]
    pub fn to_string_js(&self) -> String {
        self.inner.encode()
    }

    /// Structural equality, compared through the canonical encoding — see [`LiquersQuery::equals`].
    ///
    /// This doubles as the hash contract (`OBJECT02`): two keys that are `equals` encode
    /// identically, so the encoding is a usable map key in JavaScript, where wrapper identity is
    /// not.
    pub fn equals(&self, other: &LiquersKey) -> bool {
        self.inner.encode() == other.inner.encode()
    }

    #[wasm_bindgen(js_name = isEmpty)]
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    /// The parent key. The parent of an empty key is an empty key.
    pub fn parent(&self) -> LiquersKey {
        LiquersKey {
            inner: self.inner.parent(),
        }
    }

    /// The final path segment, when there is one.
    #[wasm_bindgen(getter)]
    pub fn filename(&self) -> Option<String> {
        self.inner.filename().map(|f| f.encode().to_string())
    }

    /// Resolves this key against a working directory.
    #[wasm_bindgen(js_name = toAbsolute)]
    pub fn to_absolute(&self, cwd: &LiquersKey) -> LiquersKey {
        LiquersKey {
            inner: self.inner.to_absolute(&cwd.inner),
        }
    }
}

impl LiquersKey {
    pub fn inner(&self) -> &Key {
        &self.inner
    }

    pub fn from_key(inner: Key) -> Self {
        LiquersKey { inner }
    }
}
