//! The `RecordBatch` handle: a wasm-safe, zero-copy-on-the-fast-path view into a Liquers record
//! batch's columnar buffers.
//!
//! See `specs/design/record-streams/phase2-architecture.md` §"The wasm route: a dedicated safe
//! mechanism, not Arrow" for the design this implements, and its §"Construction helpers, options
//! and the provider chain" for the exact Rust-side surface pinned here.
//!
//! # The two hazards, and how this handle answers them
//!
//! - **Hazard A — the heap grows.** `memory.grow` detaches the JavaScript `ArrayBuffer` but never
//!   moves the underlying pages, so a stale view is a `view.buffer !== memory.buffer` check away
//!   from detection, and the fix is re-creating the view at the *same* pointer and length. This
//!   handle does nothing special for it — the descriptor never caches a view, only the pointer and
//!   length a caller (or the `RecordColumn` companion, `records_column.js`) turns into one.
//! - **Hazard B — the buffer is freed or moved.** Prevented, not detected: [`LiquersRecordBatch`]
//!   holds an `Arc<RecordBatch>`, and every buffer inside it is `Arc`-shared and immutable once
//!   built, so as long as JavaScript holds this handle the pointers a descriptor hands out stay
//!   valid. `free()` (generated by `wasm-bindgen`) drops the `Arc`; a typed-array view held past
//!   that point is Hazard B with no detection — the caller's discipline, documented rather than
//!   enforced.
//!
//! A `RecordView` that is not already a `RecordBatch` is materialized before it reaches this
//! handle (`default_value.rs`'s `to_js_custom`) — free for a batch, and the only way to give
//! JavaScript stable pointers into a view's *computed* columns.
//!
//! # Descriptors read the batch's own storage, not a copy
//!
//! [`LiquersRecordBatch::column`] reads `self.inner.columns[i]` directly rather than going through
//! [`liquers_lib::records::RecordView::column`], whose default/`RecordBatch` implementation calls
//! `Column::slice`, which **copies** (documented on `Column::slice` as
//! `COLUMN-SLICE-COPIES-INSTEAD-OF-SHARING-BUFFER-STORAGE`). A descriptor built from that copy would point
//! into a `Column` value that is dropped the moment this function returns — a pointer to freed
//! memory before the caller ever reads it. Reading `inner.columns[i]` by reference keeps the
//! pointer inside the buffer the handle's own `Arc<RecordBatch>` keeps alive.

use std::sync::Arc;

use liquers_core::error::{Error, ErrorType};
use liquers_lib::records::{AlignedBuffer, Bitmap, Buffer, Column, RecordBatch};
use wasm_bindgen::prelude::*;

use crate::error::liquers_error_to_js;
use crate::typescript::JsRecordColumnDescriptor;

/// The JavaScript-side `RecordColumn` companion (`records_column.js`), imported as a local
/// snippet so wasm-bindgen copies it into the package's `snippets/` directory. Bound here only so
/// [`LiquersRecordBatch::column_view`] can hand back a ready-made instance; a caller is equally
/// free to build one itself from [`LiquersRecordBatch::column`]'s descriptor and its own reference
/// to `WebAssembly.Memory` — this binding is a convenience, not the only way in.
#[wasm_bindgen(module = "/src/records_column.js")]
extern "C" {
    #[wasm_bindgen(js_name = RecordColumn)]
    type JsRecordColumn;

    #[wasm_bindgen(constructor, js_class = "RecordColumn")]
    fn new(memory: &JsValue, desc: &JsValue) -> JsRecordColumn;
}

#[cfg(feature = "debug-handles")]
static LIVE_BATCH_HANDLES: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

/// Live [`LiquersRecordBatch`] handles — `RUNTIME05`'s idiom (`command::adapter::live_handle_count`),
/// applied to batches. Test-only, behind `debug-handles`: `RECORDS06` asserts it returns to
/// baseline after `free()`, which is the only way a JavaScript caller can observe that the `Arc`
/// was actually dropped rather than merely unreferenced.
#[cfg(feature = "debug-handles")]
pub fn live_batch_handle_count() -> usize {
    LIVE_BATCH_HANDLES.load(std::sync::atomic::Ordering::SeqCst)
}

/// A Liquers record batch, visible to JavaScript.
///
/// Holds the batch by `Arc`, which is the whole of Hazard B's answer — see the module
/// documentation. Cloning a `LiquersRecordBatch` (there is no such method; construct a new one
/// from the same `Arc<RecordBatch>` instead) would share the same guarantee.
#[wasm_bindgen(js_name = RecordBatch)]
pub struct LiquersRecordBatch {
    inner: Arc<RecordBatch>,
}

#[wasm_bindgen(js_class = RecordBatch)]
impl LiquersRecordBatch {
    #[wasm_bindgen(getter, js_name = numRows)]
    pub fn num_rows(&self) -> usize {
        self.inner.len
    }

    #[wasm_bindgen(getter, js_name = numColumns)]
    pub fn num_columns(&self) -> usize {
        self.inner.columns.len()
    }

    /// The batch's schema, as JSON (`RecordSchema`'s own `Serialize`).
    ///
    /// Returns `"{}"` on the serialization failure that never happens in practice — every field
    /// `RecordSchema` carries is `Serialize` — rather than a `String`-returning method having no
    /// `Result` to propagate one through; see the "no `unwrap`/`expect`" rule this avoids.
    #[wasm_bindgen(js_name = schemaJson)]
    pub fn schema_json(&self) -> String {
        serde_json::to_string(self.inner.schema.as_ref()).unwrap_or_else(|_| "{}".to_string())
    }

    /// Descriptor for column `i`: `{ kind, ptr, len, validity }`, plus `dim` for `"Vector"` and
    /// `offsets`/`data` for `"Text"`/`"Binary"` in place of `ptr`/`len`. See
    /// [`LiquersRecordColumnDescriptor`](crate::typescript::JsRecordColumnDescriptor)'s
    /// TypeScript declaration for the full shape. Carries no data itself — building a typed-array
    /// view from it is the caller's job (or `RecordColumn`'s, `records_column.js`).
    pub fn column(&self, i: usize) -> Result<JsRecordColumnDescriptor, JsValue> {
        column_descriptor(&self.inner, i)
            .map(|obj| obj.unchecked_into())
            .map_err(liquers_error_to_js)
    }

    /// The always-safe fallback: an owned copy, detached from linear memory. O(n). See
    /// [`LiquersRecordColumnCopy`](crate::typescript::JsRecordColumnCopy)'s TypeScript declaration
    /// (injected into `liquers_web.d.ts` for documentation) for exactly what each column kind
    /// copies to.
    ///
    /// Returns a plain `JsValue` rather than the `JsRecordColumnCopy` alias `column()` uses:
    /// unlike a descriptor, a copy is meant to be `dyn_into::<SpecificType>()`'d immediately, and
    /// `dyn_into`'s `Err` side is `Self` — a wrapper type with no `Debug` impl would make that
    /// call's `.expect(...)` fail to compile for every caller, Rust or JavaScript-facing alike.
    #[wasm_bindgen(js_name = columnCopy)]
    pub fn column_copy(&self, i: usize) -> Result<JsValue, JsValue> {
        column_copy(&self.inner, i).map_err(liquers_error_to_js)
    }

    /// A ready-made `RecordColumn` companion (`records_column.js`) for column `i`, built from
    /// this module's own linear memory ([`wasm_bindgen::memory`]) and [`Self::column`]'s
    /// descriptor. Purely a convenience over constructing one by hand.
    #[wasm_bindgen(js_name = columnView)]
    pub fn column_view(&self, i: usize) -> Result<JsValue, JsValue> {
        let descriptor = self.column(i)?;
        let memory = wasm_bindgen::memory();
        Ok(JsRecordColumn::new(&memory, descriptor.as_ref()).into())
    }
}

impl From<Arc<RecordBatch>> for LiquersRecordBatch {
    fn from(inner: Arc<RecordBatch>) -> Self {
        #[cfg(feature = "debug-handles")]
        LIVE_BATCH_HANDLES.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        LiquersRecordBatch { inner }
    }
}

#[cfg(feature = "debug-handles")]
impl Drop for LiquersRecordBatch {
    fn drop(&mut self) {
        LIVE_BATCH_HANDLES.fetch_sub(1, std::sync::atomic::Ordering::SeqCst);
    }
}

/// Row `i` is valid (non-null) — `None` means no validity buffer at all, every row valid. A
/// free-standing copy of `Column`'s own private helper: that one is not part of this crate's
/// public surface, and duplicating a five-line predicate is cheaper than widening it.
fn is_row_valid(validity: &Option<Bitmap>, i: usize) -> bool {
    match validity {
        Some(bitmap) => bitmap.get(i),
        None => true,
    }
}

/// Sets one property on a plain object, reporting the (practically unreachable — the key is
/// always a valid property name and the object is never frozen) failure as a typed [`Error`]
/// rather than swallowing it, following `command/adapter.rs`'s `call_js_command` convention.
fn set(obj: &js_sys::Object, key: &str, value: &JsValue) -> Result<(), Error> {
    js_sys::Reflect::set(obj, &JsValue::from_str(key), value)
        .map(|_| ())
        .map_err(|_| {
            Error::from_error(
                ErrorType::ConversionError,
                format!("Could not set {key:?} on a record column descriptor"),
            )
        })
}

/// A plain `{ kind, ptr, len }` descriptor — the shape every leaf of
/// [`JsRecordColumnDescriptor`](crate::typescript::JsRecordColumnDescriptor) shares.
fn leaf_descriptor(kind: &str, ptr: usize, len: usize) -> Result<js_sys::Object, Error> {
    let obj = js_sys::Object::new();
    set(&obj, "kind", &JsValue::from_str(kind))?;
    set(&obj, "ptr", &JsValue::from_f64(ptr as f64))?;
    set(&obj, "len", &JsValue::from_f64(len as f64))?;
    Ok(obj)
}

/// The `validity` field: `null`, or a `"Bitmap"`-kind leaf descriptor over the packed bytes.
///
/// `len` on that leaf is the **byte** length of the packed storage (`bitmap.as_bytes().len()`),
/// consistent with every other leaf's `len` meaning "elements of `kind` at `ptr`" — a `"Bitmap"`
/// element is a byte. `rows` carries the logical bit count separately, since `len.saturating_mul(8)`
/// may overcount by up to 7 padding bits in the last byte.
fn validity_descriptor(validity: &Option<Bitmap>) -> Result<JsValue, Error> {
    match validity {
        None => Ok(JsValue::NULL),
        Some(bitmap) => {
            let bytes = bitmap.as_bytes();
            let obj = leaf_descriptor("Bitmap", bytes.as_ptr() as usize, bytes.len())?;
            set(&obj, "rows", &JsValue::from_f64(bitmap.len() as f64))?;
            Ok(obj.into())
        }
    }
}

/// A column descriptor built from one leaf plus `validity`, and any further fields a kind needs
/// (`dim` for `"Vector"`'s row width, `rows` for `"BoolBitmap"`'s logical bit count).
fn numeric_descriptor(
    kind: &str,
    ptr: usize,
    len: usize,
    extra: &[(&str, f64)],
    validity: &Option<Bitmap>,
) -> Result<js_sys::Object, Error> {
    let obj = leaf_descriptor(kind, ptr, len)?;
    for (key, value) in extra {
        set(&obj, key, &JsValue::from_f64(*value))?;
    }
    set(&obj, "validity", &validity_descriptor(validity)?)?;
    Ok(obj)
}

/// `Text`/`Binary`'s descriptor: no top-level `ptr`/`len` (there are two buffers), an `offsets`
/// leaf (`"Int32"`, `numRows + 1` entries) and a `data` leaf (`"Uint8"`, the concatenated bytes).
fn byte_column_descriptor(
    kind: &str,
    validity: &Option<Bitmap>,
    offsets: &Buffer<i32>,
    data: &AlignedBuffer,
) -> Result<js_sys::Object, Error> {
    let obj = js_sys::Object::new();
    set(&obj, "kind", &JsValue::from_str(kind))?;
    let off = offsets.as_slice();
    let offsets_desc = leaf_descriptor("Int32", off.as_ptr() as usize, off.len())?;
    set(&obj, "offsets", &offsets_desc.into())?;
    let bytes = data.as_bytes();
    let data_desc = leaf_descriptor("Uint8", bytes.as_ptr() as usize, bytes.len())?;
    set(&obj, "data", &data_desc.into())?;
    set(&obj, "validity", &validity_descriptor(validity)?)?;
    Ok(obj)
}

/// The column at `i`, borrowed straight out of the batch's own storage — see the module
/// documentation for why this bypasses `RecordView::column`.
fn column_of(batch: &RecordBatch, i: usize) -> Result<&Column, Error> {
    batch.columns.get(i).ok_or_else(|| {
        Error::general_error(format!(
            "RecordBatch::column: column index {i} out of range (0..{})",
            batch.columns.len()
        ))
    })
}

/// Builds the descriptor object for [`LiquersRecordBatch::column`]. Exhaustive over every
/// [`Column`] variant — CLAUDE.md's "Match Statements" convention forbids a default arm on a
/// Liquers-owned enum, so a future `Column` kind is a compile error here, not a silently missing
/// descriptor.
fn column_descriptor(batch: &RecordBatch, i: usize) -> Result<js_sys::Object, Error> {
    match column_of(batch, i)? {
        Column::Int { validity, values } => {
            let slice = values.as_slice();
            numeric_descriptor("Int", slice.as_ptr() as usize, slice.len(), &[], validity)
        }
        Column::UInt { validity, values } => {
            let slice = values.as_slice();
            numeric_descriptor("UInt", slice.as_ptr() as usize, slice.len(), &[], validity)
        }
        Column::Float { validity, values } => {
            let slice = values.as_slice();
            numeric_descriptor("Float", slice.as_ptr() as usize, slice.len(), &[], validity)
        }
        Column::Date { validity, values } => {
            let slice = values.as_slice();
            numeric_descriptor("Date", slice.as_ptr() as usize, slice.len(), &[], validity)
        }
        Column::Timestamp { validity, values } => {
            let slice = values.as_slice();
            numeric_descriptor("Timestamp", slice.as_ptr() as usize, slice.len(), &[], validity)
        }
        Column::Vector { validity, dim, data } => {
            let slice = data.as_slice();
            let extra = [("dim", *dim as f64)];
            numeric_descriptor("Vector", slice.as_ptr() as usize, slice.len(), &extra, validity)
        }
        Column::Bool { validity, values } => {
            // Bit-packed: `len` is the *byte* length of the packed storage (matching every other
            // leaf's "elements of `kind` at `ptr`"), and `rows` carries the logical bit count
            // separately — the "BoolBitmap" kind exists so a caller cannot mistake this pointer
            // for one byte per row.
            let bytes = values.as_bytes();
            let extra = [("rows", values.len() as f64)];
            numeric_descriptor("BoolBitmap", bytes.as_ptr() as usize, bytes.len(), &extra, validity)
        }
        Column::Text { validity, offsets, data } => byte_column_descriptor("Text", validity, offsets, data),
        Column::Binary { validity, offsets, data } => {
            byte_column_descriptor("Binary", validity, offsets, data)
        }
    }
}

/// Builds the owned copy for [`LiquersRecordBatch::column_copy`]. Exhaustive over every [`Column`]
/// variant for the same reason as [`column_descriptor`].
fn column_copy(batch: &RecordBatch, i: usize) -> Result<JsValue, Error> {
    match column_of(batch, i)? {
        Column::Int { values, .. } => Ok(js_sys::BigInt64Array::from(values.as_slice()).into()),
        Column::UInt { values, .. } => Ok(js_sys::BigUint64Array::from(values.as_slice()).into()),
        Column::Float { values, .. } => Ok(js_sys::Float64Array::from(values.as_slice()).into()),
        Column::Date { values, .. } => Ok(js_sys::Int32Array::from(values.as_slice()).into()),
        Column::Timestamp { values, .. } => Ok(js_sys::BigInt64Array::from(values.as_slice()).into()),
        // Unpacked to one byte (0/1) per row — a fast, null-blind raw copy, like the other
        // numeric kinds above. `column`'s `validity` descriptor is the way to learn which rows
        // are actually null; `columnCopy` never distinguishes them for any numeric kind.
        Column::Bool { values, .. } => {
            let unpacked: Vec<u8> = (0..values.len()).map(|row| values.get(row) as u8).collect();
            Ok(js_sys::Uint8Array::from(unpacked.as_slice()).into())
        }
        Column::Text { validity, offsets, data } => text_copy(validity, offsets, data),
        Column::Binary { validity, offsets, data } => binary_copy(validity, offsets, data),
        Column::Vector { validity, dim, data } => vector_copy(validity, *dim, data),
    }
}

/// `Text`'s copy: an array of JavaScript strings, `null` for a null cell — chosen over a typed
/// array because there is no typed array of variable-length UTF-8 strings.
fn text_copy(validity: &Option<Bitmap>, offsets: &Buffer<i32>, data: &AlignedBuffer) -> Result<JsValue, Error> {
    let off = offsets.as_slice();
    let bytes = data.as_bytes();
    let rows = off.len().saturating_sub(1);
    let array = js_sys::Array::new();
    for row in 0..rows {
        if !is_row_valid(validity, row) {
            array.push(&JsValue::NULL);
            continue;
        }
        let start = off[row] as usize;
        let end = off[row + 1] as usize;
        let text = std::str::from_utf8(&bytes[start..end])
            .map_err(|e| Error::from_error(ErrorType::ConversionError, e))?;
        array.push(&JsValue::from_str(text));
    }
    Ok(array.into())
}

/// `Binary`'s copy: an array of per-row `Uint8Array`s, `null` for a null cell — chosen over a
/// single flat `Uint8Array` because each row's byte length differs and a caller needs the
/// boundary, which `columnCopy` (unlike `column`) does not separately expose.
fn binary_copy(
    validity: &Option<Bitmap>,
    offsets: &Buffer<i32>,
    data: &AlignedBuffer,
) -> Result<JsValue, Error> {
    let off = offsets.as_slice();
    let bytes = data.as_bytes();
    let rows = off.len().saturating_sub(1);
    let array = js_sys::Array::new();
    for row in 0..rows {
        if !is_row_valid(validity, row) {
            array.push(&JsValue::NULL);
            continue;
        }
        let start = off[row] as usize;
        let end = off[row + 1] as usize;
        array.push(&js_sys::Uint8Array::from(&bytes[start..end]).into());
    }
    Ok(array.into())
}

/// `Vector`'s copy: an array of per-row `Float32Array`s (each `dim` elements), `null` for a null
/// cell — chosen over one flat `Float32Array` so a row's boundary survives the copy without a
/// caller having to know `dim` separately.
fn vector_copy(validity: &Option<Bitmap>, dim: usize, data: &Buffer<f32>) -> Result<JsValue, Error> {
    let slice = data.as_slice();
    let rows = if dim == 0 { 0 } else { slice.len() / dim };
    let array = js_sys::Array::new();
    for row in 0..rows {
        if !is_row_valid(validity, row) {
            array.push(&JsValue::NULL);
            continue;
        }
        let start = row * dim;
        let end = start + dim;
        array.push(&js_sys::Float32Array::from(&slice[start..end]).into());
    }
    Ok(array.into())
}
