//! `OBJECT*` and `ERROR*` conformance tests.
//!
//! Pure value/parse semantics — no DOM — so these run under Node. See
//! `specs/liquers-web/phase3-examples.md` for the inventory.

#![cfg(target_arch = "wasm32")]

use liquers_core::error::ErrorType;
use liquers_web::error::{error_type_from_name, error_type_name, LiquersError};
use liquers_web::{LiquersKey, LiquersQuery};
use wasm_bindgen::prelude::*;
use wasm_bindgen_test::*;

/// Every `ErrorType` variant. Listed explicitly rather than iterated, because the enum has no
/// iterator — if a variant is added, `error_type_name`'s exhaustive match fails to compile, and
/// this list is then updated to match.
const ALL_ERROR_TYPES: &[ErrorType] = &[
    ErrorType::ArgumentMissing,
    ErrorType::ActionNotRegistered,
    ErrorType::CommandAlreadyRegistered,
    ErrorType::ParseError,
    ErrorType::ParameterError,
    ErrorType::TooManyParameters,
    ErrorType::ConversionError,
    ErrorType::SerializationError,
    ErrorType::General,
    ErrorType::CacheNotSupported,
    ErrorType::UnknownCommand,
    ErrorType::NotSupported,
    ErrorType::NotAvailable,
    ErrorType::KeyNotFound,
    ErrorType::KeyNotSupported,
    ErrorType::KeyReadError,
    ErrorType::KeyWriteError,
    ErrorType::UnexpectedError,
    ErrorType::ExecutionError,
    ErrorType::DependencyVersionMismatch,
    ErrorType::DependencyCycle,
    ErrorType::Cancelled,
];

/// OBJECT01 — query parse/encode round-trips.
#[wasm_bindgen_test]
fn object01_query_parse_encode_roundtrip() {
    for text in ["hello", "hello/greet", "hello/repeat-3", "hello/ns-myapp/shout"] {
        let q = LiquersQuery::parse(text).expect("parse");
        assert_eq!(q.encode(), text, "round trip changed the query");
        assert_eq!(q.to_string_js(), text, "toString must agree with encode");
    }
}

/// OBJECT02 — key equality and the hash contract.
#[wasm_bindgen_test]
fn object02_key_equality_and_hash() {
    let a = LiquersKey::parse("d/f").expect("parse a");
    let b = LiquersKey::parse("d/f").expect("parse b");
    let c = LiquersKey::parse("d/g").expect("parse c");

    assert!(a.equals(&b), "equal keys must compare equal");
    assert!(!a.equals(&c));
    // The hash contract: equal keys encode identically, so the encoding is a usable map key.
    assert_eq!(a.encode(), b.encode());
    assert_ne!(a.encode(), c.encode());

    assert_eq!(a.parent().encode(), "d");
    assert_eq!(a.filename().as_deref(), Some("f"));
}

/// OBJECT03 — command metadata round-trips.
///
/// Scoped to what this milestone exposes: the version surface, which is the metadata a caller can
/// currently read. Widens when M4 adds `describeCommand`.
#[wasm_bindgen_test]
fn object03_command_metadata_roundtrip() {
    let v = liquers_web::version();
    assert!(v.contains("liquers-web"), "version should name the crate: {v}");
    assert!(v.contains("liquers-core"), "version should name the core: {v}");
}

/// OBJECT04 — invalid parse produces a structured error, not a panic or a bare string.
#[wasm_bindgen_test]
fn object04_invalid_parse_produces_error() {
    let err = match LiquersQuery::parse("hello/a:b") {
        Err(e) => e,
        Ok(_) => panic!("a colon is not valid query text and must not parse"),
    };
    let name = js_sys::Reflect::get(&err, &"errorType".into())
        .expect("errorType readable")
        .as_string()
        .expect("errorType is a string");
    assert_eq!(name, "parse_error");

    let message = js_sys::Reflect::get(&err, &"message".into())
        .expect("message readable")
        .as_string()
        .expect("message is a string");
    assert!(!message.is_empty(), "a parse error must say something");
}

/// OBJECT05 — a wrapper stays valid for its documented lifetime.
///
/// The documented lifetime is "until `free()`". Using a freed handle throws — that behaviour is
/// generated by `wasm-bindgen` and is asserted here rather than reimplemented.
#[wasm_bindgen_test]
fn object05_wrapper_valid_for_documented_lifetime() {
    let q = LiquersQuery::parse("hello/greet").expect("parse");
    // Valid across many uses.
    for _ in 0..100 {
        assert_eq!(q.encode(), "hello/greet");
    }
    // Still valid after an unrelated wrapper is dropped.
    {
        let _other = LiquersQuery::parse("hello").expect("parse");
    }
    assert_eq!(q.encode(), "hello/greet");
}

/// OBJECT06 — every enum variant round-trips by name.
#[wasm_bindgen_test]
fn object06_every_enum_variant_roundtrips() {
    assert_eq!(ALL_ERROR_TYPES.len(), 22, "ErrorType variant count changed");
    for t in ALL_ERROR_TYPES {
        let name = error_type_name(*t);
        assert!(!name.is_empty());
        assert_eq!(
            error_type_from_name(name),
            Some(*t),
            "{name} did not round trip"
        );
    }
    // Names must be distinct, or the mapping is not a bijection.
    let mut names: Vec<&str> = ALL_ERROR_TYPES.iter().map(|t| error_type_name(*t)).collect();
    names.sort_unstable();
    let count = names.len();
    names.dedup();
    assert_eq!(names.len(), count, "two ErrorType variants share a name");
}

/// OBJECT07 — an unknown enum name from JavaScript follows the compatibility policy.
///
/// The policy is that an unrecognised name is *reported*, never silently mapped to a default: a
/// name from a newer Liquers must not quietly become `General`.
#[wasm_bindgen_test]
fn object07_unknown_enum_variant_follows_policy() {
    assert_eq!(error_type_from_name("a_variant_from_the_future"), None);
    assert_eq!(error_type_from_name(""), None);
    assert_eq!(error_type_from_name("General"), None, "matching is exact");
}

/// OBJECT08 — wrappers follow the documented naming and ownership conventions.
#[wasm_bindgen_test]
fn object08_wrappers_follow_naming_and_ownership_conventions() {
    // Construction is through the Rust parser, never a JavaScript reimplementation.
    let q = LiquersQuery::parse("hello/greet").expect("parse");
    let k = LiquersKey::parse("d/f").expect("parse");

    // Every wrapper offers encode() and toString(), and they agree.
    assert_eq!(q.encode(), q.to_string_js());
    assert_eq!(k.encode(), k.to_string_js());

    // Wrappers are immutable: an operation that would change one returns a new wrapper and leaves
    // the original alone.
    let parent = k.parent();
    assert_eq!(k.encode(), "d/f", "parent() must not mutate the receiver");
    assert_eq!(parent.encode(), "d");
}

/// ERROR01 — every `ErrorType` maps to a language-visible error.
#[wasm_bindgen_test]
fn error01_every_error_type_maps() {
    for t in ALL_ERROR_TYPES {
        let err = liquers_core::error::Error::from_error(*t, "test".to_string());
        let wrapped = LiquersError::new(err);
        assert_eq!(wrapped.error_type(), error_type_name(*t));
        assert_eq!(wrapped.message(), "test");
    }
}

/// ERROR02 — fields survive Rust → JavaScript → Rust.
#[wasm_bindgen_test]
fn error02_fields_survive_rust_language_rust() {
    let err = liquers_core::error::Error::from_error(
        ErrorType::KeyNotFound,
        "no such key".to_string(),
    );
    let js = liquers_web::error::liquers_error_to_js(err);

    // Out to JavaScript.
    let name = js_sys::Reflect::get(&js, &"errorType".into())
        .expect("errorType")
        .as_string()
        .expect("string");
    assert_eq!(name, "key_not_found");

    // And back into Rust, without accumulating wrapping.
    let back = liquers_web::error::js_error_to_liquers(js, ErrorType::General);
    assert_eq!(back.error_type, ErrorType::KeyNotFound, "type must survive");
    assert_eq!(back.message, "no such key", "message must survive verbatim");
}

/// ERROR03 — a JavaScript exception carries its class and stack across.
#[wasm_bindgen_test]
fn error03_language_exception_includes_class_and_stack() {
    let thrown: JsValue = js_sys::Error::new("boom").into();
    let wrapped = LiquersError::from_thrown(thrown, ErrorType::ExecutionError);

    assert_eq!(wrapped.error_type(), "execution_error");
    assert!(
        wrapped.message().contains("boom"),
        "the thrown message must survive: {}",
        wrapped.message()
    );
    assert_eq!(
        wrapped.js_class().as_deref(),
        Some("Error"),
        "the originating class must be preserved in its own field, not only in the message"
    );
    assert!(
        wrapped.js_stack().is_some(),
        "the originating stack must be preserved in its own field"
    );
}

/// ERROR04 — a non-`Error` throw has a safe fallback.
#[wasm_bindgen_test]
fn error04_non_error_throw_has_safe_fallback() {
    // `throw 42`
    let e = liquers_web::error::js_error_to_liquers(JsValue::from_f64(42.0), ErrorType::ExecutionError);
    assert_eq!(e.error_type, ErrorType::ExecutionError);
    assert!(e.message.contains("42"), "the thrown value should be reported: {}", e.message);

    // `throw undefined` — no useful string form, so it must say what happened instead of empty.
    let e = liquers_web::error::js_error_to_liquers(JsValue::UNDEFINED, ErrorType::ExecutionError);
    assert!(!e.message.is_empty(), "undefined throw must still produce a message");

    // A conversion boundary reports a conversion failure, not an execution failure.
    let e = liquers_web::error::js_error_to_liquers(JsValue::from_str("nope"), ErrorType::ConversionError);
    assert_eq!(
        e.error_type,
        ErrorType::ConversionError,
        "the fallback type must be honoured; a conversion failure is not an execution failure"
    );
}

/// ERROR05 — no panic crosses the boundary.
///
/// Every fallible entry point returns `Result`, so a failure surfaces as a thrown `LiquersError`
/// rather than as a wasm abort. Exercised here against inputs that fail.
#[wasm_bindgen_test]
fn error05_no_panic_crosses_the_boundary() {
    assert!(LiquersQuery::parse("hello/a:b").is_err());
    assert!(LiquersQuery::parse("").is_ok(), "an empty query is legal");
    assert!(LiquersKey::parse("\u{0}").is_err() || LiquersKey::parse("\u{0}").is_ok());
    // Reaching here at all is the assertion: none of the above aborted the module.
}
